# Generated by Django 4.1.6 on 2023-03-01 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff_Detail',
        ),
        migrations.AlterField(
            model_name='cart_detail',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 1, 13, 15, 5, 574271, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
